@baseUrl = https://ereport.local/api/v1
@baseUrl = http://localhost:8085/api/v1
@baseUrl = https://e-reportpoldakalbar.id/api/v1
@token = grsosr7ov6mmt84k5m1av95od2

### Satker (Login)
POST {{baseUrl}}/ereport/satker/login
token: {{token}}
Content-Type: application/x-www-form-urlencoded

satker=54TYD&password=ereport

### Satker (Form Add/Edit)
POST {{baseUrl}}/ereport/satker/form
token: {{token}}
Content-Type: application/x-www-form-urlencoded

# id=54TYD
id=

### Satker (List)
POST {{baseUrl}}/ereport/satker/list
token: {{token}}
Content-Type: application/x-www-form-urlencoded

page=1&size=0&cari=&group=

### Satker (Save)
POST {{baseUrl}}/ereport/satker/save
token: {{token}}
Content-Type: application/x-www-form-urlencoded

# id_satker=54TYD&nama_satker=Polresta Pontianak Kota&group_satker=&password=ereport
# id_satker=H9XOF&nama_satker=Polsek Pontianak Barat&group_satker=54TYD&password=ereport
# id_satker=UFZHT&nama_satker=Polsek Pontianak Selatan&group_satker=54TYD&password=ereport
# id_satker=7QXVP&nama_satker=Polresta Singkawang&group_satker=&password=ereport
# id_satker=Q15SC&nama_satker=Polsek Singkawang Barat&group_satker=7QXVP&password=ereport
# id_satker=SLGDB&nama_satker=Polsek Singkawang Tengah&group_satker=7QXVP&password=ereport
# id_satker=2L8J1&nama_satker=Polresta Landak&group_satker=&password=ereport
# id_satker=N8K8V&nama_satker=Polsek Sebangki&group_satker=2L8J1&password=ereport
# id_satker=WRMUH&nama_satker=Polsek Ngabang&group_satker=2L8J1&password=ereport

### Form Cek Tahanan
POST {{baseUrl}}/ereport/tahanan/form
token: {{token}}
Content-Type: application/x-www-form-urlencoded

satker=54TYD

### Entry Form Cek Tahanan
POST {{baseUrl}}/ereport/tahanan/entry
token: {{token}}
Content-Type: application/json

{
    "id_cek_tahanan": "HH1CK5HM0O",
    "satker_id": "54TYD",
    "jumlah_tahanan": "10",
    "surat_aktif": "10",
    "surat_expired": "0",
    "kamar_mandi": "Air Mengalir",
    "dinding_tembok": "Baik",
    "jeruji": "Baik",
    "material_platfon": "Cor Beton",
    "jendela_ventilasi": "Baik",
    "cctv": "Ada (Aktif)",
    "barang_temuan": "",
    "hal_menonjol": "",
    "datetime": "2021-03-08 22:27:07"
}

### Upload Form Cek Tahanan
POST {{baseUrl}}/ereport/tahanan/upload
token: {{token}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary7MA4YWxkTrZu0gW

--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="id_document_upload"

20210308235956
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="cek_id"

HH1CK5HM0O
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="category_document"

CT01
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="text_caption"


--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="file_upload"


--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="latitude"


--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="longitude"


--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="datetime"


--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image_0"; filename="img_1.jpg"
Content-Type: image/jpg

< ./people/img_1.jpg
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image_1"; filename="img_2.jpg"
Content-Type: image/jpg

< ./people/img_2.jpg
--WebKitFormBoundary7MA4YWxkTrZu0gW--

### Form Cek Kebakaran
POST {{baseUrl}}/ereport/kebakaran/form
token: {{token}}
Content-Type: application/x-www-form-urlencoded

satker=54TYD

### Entry Form Cek Kebakaran
POST {{baseUrl}}/ereport/kebakaran/entry
token: {{token}}
Content-Type: application/json

{
    "id_cek_kebakaran": "6MBTDZSMGZ",
    "satker_id": "54TYD",
    "hal_menonjol": "OK",
    "datetime": "2021-03-09 09:41:36"
}

### Upload Form Cek Kebakaran
POST {{baseUrl}}/ereport/kebakaran/upload
token: {{token}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary7MA4YWxkTrZu0gW

--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="id_document_upload"

20210309095603
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="cek_id"

6MBTDZSMGZ
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="satker_id"

54TYD
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="category_document"

CK01
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="text_caption"


--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="file_upload"


--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="latitude"


--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="longitude"


--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Type: text/plain
Content-Disposition: form-data; name="datetime"


--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image_0"; filename="img_1.jpg"
Content-Type: image/jpg

< ./people/img_1.jpg
--WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image_1"; filename="img_2.jpg"
Content-Type: image/jpg

< ./people/img_2.jpg
--WebKitFormBoundary7MA4YWxkTrZu0gW--